# Site settings
course_name: Introduction To Computer Science
course_description: "Computers play an essential part in our daily life and we will learn the basic ideas behind your laptop and smartphone. Specifically, we will give an overview of the computer science landscape, including the hardware, software, and applications. We will also cover basic programming language (Python) in the second half of the semester."
course_semester: "Fall 2022"

baseurl: "/nsysu-math105A/" # the subpath of your site, e.g. /blog/
url: "https://phonchi.github.io/" # the base hostname & protocol for your site

schoolname: "National Sun Yat-Sen University"
schoolurl: "https://www.nsysu.edu.tw/"
#twitter_username: username 

address: |
    No.70 Lien-hai Rd., Kaohsiung 80424, 
    Taiwan

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
